### ISSUE TITLE
Not getting this to work on an Adafruit Feather m0 datalogger

### ISSUE THREAD

**Issue by frippe75** [ericbaril72/SAMD21-SDBootloader#2]
Hi Eric.

Been trying to compile the bootloader for a custom pcb with the D21. Have different pin mappings so I just bought an Adafruit m0 datalogger just to try the bootloader you supplied in the build directory out.

Compiled a simple blink.bin which I placed on the SD card (2GB FAT) as fd.bin

Created a custom entry by cloning the entry in boards.txt.

**Made two changes to the new "custom" board:**
```
arduino_custom_native.build.ldscript=linker_scripts/gcc/flash_with_bootloader_32kb.ld
arduino_custom_native.bootloader.file=custom_board/custom.bin
```

custom.bin being the bootloader from the build dir.
copied the **flash_with_bootloader.ld** -> **flash_with_bootloader_32kb.ld**

**Changed the following:**
```
MEMORY
{
  FLASH (rx) : ORIGIN = 0x00000000+0x8000, LENGTH = 0x00040000-0x8000 /* First 32KB used by bootloader */
  RAM (rwx) : ORIGIN = 0x20000000, LENGTH = 0x00008000
}

```

After uploading the sketch (blink) via Arduino IDE. It completes the upload and then.... nothing.
Board disapears as USB device for ever. Am I missing something? Thanks for your support!

**Comment by frippe75** [comment]
Have you programmed this "oversized" bootloader successfully via Arduino IDE?
Because it calls bossac with -e which erase the chip from 8KB ->

There is an issue logged for bossac to allow support for bigger bootloaders
https://github.com/shumatech/BOSSA/issues/33

**Comment by ericbaril72** [comment]
You are correct, the Adafruit boards have the bootprot fuse bits set to
protect the first section.

I have a J-link.

And there is still light at the end of the tunnel.

The UF2 bootloader comes with an arduino sketch that lets you update the
original bootloader (including flipping the bootprot bits). So
cut-and-paste from this sketch src code.

It reads the fuses , updates the fuses and reads them again. You should be
able to move forward.

Sorry for not inserting this snippet here but always far from my computer
when I get to answer back.

Let me know if you managed through. I’ve gone trough so many bootloaders
code to understand how to do mine that it could come from Flora or some
other one.

**Comment by frippe75** [comment]
Hi Eric.

I did manage to compile the project eventually, even though it's not really working. You made some changes to the example project from Atmel. Would you say the code you have here is what you believe should be working or simply have the repo here for your reference? I think I'm finding a few of errors here and there. Do you want me to log issue or do you consider this repo "stale" ? 

I might fork it off and continue it if you've lost interest. Thanks again for responding!

**Comment by ericbaril72** [comment]
I've been using it for a while but might get back to it to "merge-it" with UF2 bootloader.
the USB interface is so much FASTER for quick development.
I use the SDbootloader for remoteWifiUpdates using the WINC1500

Noticing after a while of looking into multiple bootloaders and boards that a Pin-configuration tool might be usefull.
